# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) - do not redeclare here.

variable "resource_groups" {
  description = "Resource groups keyed by layer (e.g. network, databricks, adf, monitoring)."
  type = map(object({
    name = string
  }))
}

variable "enable_lock" {
  description = "Apply a management lock to every resource group. Single flag — flip here, not per resource group."
  type        = bool
  default     = false
}

variable "lock_level" {
  description = "Lock level applied to every resource group when enable_lock is true."
  type        = string
  default     = "CanNotDelete"

  validation {
    condition     = contains(["CanNotDelete", "ReadOnly"], var.lock_level)
    error_message = "lock_level must be \"CanNotDelete\" or \"ReadOnly\"."
  }
}
