# account_id, tenant_id, subscription_id, location, environment, location_code,
# tags are declared in globals.tf (generated by common.hcl) — do not redeclare
# here. This module talks to the Databricks account API only, via the
# aliased "account" databricks provider generated in root.hcl - it creates
# no Azure resources.

variable "network_policy_id" {
  description = "Account network policy to update. Every Databricks account has exactly one reserved account-level policy, always named \"default-policy\" - there is no separate, dedicated \"IP access list\" object. The Security > Policies > Account console IP access list page in the account console is a simplified view over this same policy's ingress.public_access rules."
  type        = string
  default     = "default-policy"
}

variable "enabled" {
  description = "false = FULL_ACCESS (any IP can reach the account console; allow_rules/block_rules below are ignored) - same as toggling \"Account console IP access list\" to Disabled. true = RESTRICTED_ACCESS, enforcing allow_rules/block_rules. Leave false until allow_rules contains at least the IP/CIDR you're applying from - enabling with an empty or wrong allow list locks every admin out of the account console, and there is no break-glass short of a support ticket."
  type        = bool
  default     = false
}

variable "allow_rules" {
  description = "ALLOW rules, keyed by a unique logical name. Each becomes an ingress.public_access allow rule scoped to the account console UI - equivalent to an ALLOW entry added via Security > Policies > Account console IP access list > Add rule."
  type = map(object({
    label        = string
    ip_addresses = list(string) # IPv4 addresses/CIDR ranges only.
  }))
  default = {}
}

variable "block_rules" {
  description = "BLOCK rules, keyed by a unique logical name. Deny rules are evaluated before allow rules - a request matching any block rule is denied regardless of allow_rules."
  type = map(object({
    label        = string
    ip_addresses = list(string) # IPv4 addresses/CIDR ranges only.
  }))
  default = {}
}
