# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) — do not redeclare here.

variable "resource_group_name" {
  description = "Resource group to deploy the workspace into (the monitoring layer's RG)."
  type        = string
}

variable "name" {
  description = "Name of the Log Analytics Workspace (4-63 characters: letters, digits, hyphens; no leading/trailing hyphens)."
  type        = string
}

variable "sku" {
  description = "Pricing tier for the workspace. PerGB2018 is the current standard SKU for new workspaces — only change this for a documented reason."
  type        = string
  default     = "PerGB2018"
}

variable "retention_in_days" {
  description = "Data retention period in days."
  type        = number
  default     = 90

  validation {
    condition     = var.retention_in_days >= 30 && var.retention_in_days <= 730
    error_message = "retention_in_days must be between 30 and 730 (Azure Log Analytics limits)."
  }
}

variable "daily_quota_gb" {
  description = "Daily ingestion cap in GB. -1 disables the cap (no daily quota)."
  type        = number
  default     = -1
}

variable "internet_ingestion_enabled" {
  description = "Allow log ingestion over the public internet. Diagnostic settings (this repo's actual ingestion path — ADF/Databricks/Storage) bypass this entirely regardless of its value, per Microsoft's docs: that traffic rides a secure Microsoft control-plane channel, not this network path."
  type        = bool
  default     = true
}

variable "internet_query_enabled" {
  description = "Allow querying the workspace over the public internet."
  type        = bool
  default     = true
}

variable "local_authentication_enabled" {
  description = "Allow workspace shared-key authentication. False forces every access path — ingestion, agents, API, portal — through Microsoft Entra ID; the shared keys become unusable even though the provider still exposes them as attributes (this module never outputs them — see 99-outputs.tf)."
  type        = bool
  default     = false
}

