# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) — do not redeclare here.

variable "resource_group_name" {
  description = "Resource group to deploy the resolver into (the hub's network RG)."
  type        = string
}

variable "project" {
  description = "Project name segment used in resource naming (e.g. alphaai)."
  type        = string
}

variable "instance" {
  description = "Instance number segment used in resource naming."
  type        = string
  default     = "001"
}

variable "virtual_network_id" {
  description = "VNet the resolver attaches to. This must be the hub VNet — the one every private DNS zone is linked to — since resolution follows the VNet the query is seen to originate from, and an inbound endpoint makes queries look like they originate here."
  type        = string
}

variable "inbound_subnet_id" {
  description = "Dedicated subnet for the inbound endpoint. Azure requires it delegated to Microsoft.Network/dnsResolvers, at least /28, and carrying no other resources — no NSG or route table may be associated with it."
  type        = string
}

variable "inbound_endpoint_private_ip" {
  description = "Static private IP for the inbound endpoint, inside inbound_subnet_id. Set this (rather than leaving it null for dynamic allocation) so spokes can point their VNet's dns_servers at a fixed, known address instead of needing a live dependency on this stack — same convention this repo already uses for firewall_private_ip."
  type        = string
  default     = null
}
