# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) — do not redeclare here.

variable "resource_group_name" {
  description = "Existing resource group to deploy into (the network layer's RG)."
  type        = string
}

variable "project" {
  description = "Project name segment used in resource naming (e.g. alphaai)."
  type        = string
}

variable "instance" {
  description = "Instance number segment used in resource naming."
  type        = string
  default     = "001"
}

variable "vnet_name" {
  description = "Override for the VNet name. Defaults to vnet-<location_code>-<environment>-<project>-<instance>."
  type        = string
  default     = null
}

variable "address_space" {
  description = "Address space for the VNet."
  type        = list(string)

  validation {
    condition     = length(var.address_space) > 0
    error_message = "At least one address space must be specified."
  }
}

variable "dns_servers" {
  description = "Custom DNS servers for the VNet."
  type        = list(string)
  default     = []
}

variable "ddos_protection_plan_id" {
  description = "DDoS protection plan ID to associate with the VNet."
  type        = string
  default     = null
}

variable "subnets" {
  description = "Subnets keyed by purpose (e.g. private-endpoints, databricks-public). Name defaults to snet-<location_code>-<environment>-<project>-<key>-<instance>."
  type = map(object({
    name                                          = optional(string)
    address_prefixes                              = list(string)
    service_endpoints                             = optional(list(string), [])
    private_endpoint_network_policies             = optional(string, "Enabled")
    private_link_service_network_policies_enabled = optional(bool, true)
    delegation = optional(object({
      name         = string
      service_name = string
      actions      = list(string)
    }), null)
  }))
  default = {}
}
