# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) — do not redeclare here.
# This module talks to one Databricks workspace's REST API only, via the
# aliased "workspace" databricks provider generated in root.hcl (its host is
# fed from the 08databricks unit's workspace_url output) - it creates no
# Azure resources.

variable "enabled" {
  description = "Whether the IP access list feature is turned on for this workspace (enableIpAccessLists workspace-conf setting). false leaves the feature off - allow_rules/block_rules below are created but have no effect until this is true. Leave false until allow_rules contains at least the IP/CIDR you're applying from: once IP access lists are enabled AND at least one ALLOW rule exists, every IP not on an allow list is blocked, including yours."
  type        = bool
  default     = false
}

variable "allow_rules" {
  description = "ALLOW rules, keyed by a unique logical name. Each becomes a databricks_ip_access_list with list_type = \"ALLOW\" - equivalent to `databricks ip-access-lists create` with list_type ALLOW. If this map is non-empty, only the IPs listed across all ALLOW rules (minus anything in block_rules) can reach the workspace once enabled = true - this must include any public IP the compute plane uses to reach the control plane (see this module's caller for secure cluster connectivity notes)."
  type = map(object({
    label        = string
    ip_addresses = list(string) # IPv4 addresses/CIDR ranges only.
  }))
  default = {}
}

variable "block_rules" {
  description = "BLOCK rules, keyed by a unique logical name. Each becomes a databricks_ip_access_list with list_type = \"BLOCK\" - excluded even if also covered by an allow_rules entry."
  type = map(object({
    label        = string
    ip_addresses = list(string) # IPv4 addresses/CIDR ranges only.
  }))
  default = {}
}
