# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) — do not redeclare here.

# ── Cloudflare account context (cannot be created — you supply these) ────────

variable "cloudflare_account_id" {
  description = "Cloudflare account ID that owns the Zero Trust org these resources are created in."
  type        = string
}

variable "cloudflare_team_name" {
  description = "Zero Trust team domain prefix (e.g. \"acme\" for acme.cloudflareaccess.com). Used to build the Entra ID app's redirect URI."
  type        = string
}

# ── Naming ────────────────────────────────────────────────────────────────────

variable "resource_suffix" {
  description = "Suffix used to name every resource this module creates (e.g. cf-hub-eus-001)."
  type        = string
}

# ── Networking ────────────────────────────────────────────────────────────────
# This module deploys into the hub's existing VNet/subnet (02environments/hub's
# 02vnet unit) rather than creating its own — resource_group_name and
# subnet_id are read from that unit via a cross-stack/autoinclude dependency
# in units/cloudflare-zero-trust/terragrunt.hcl, the same pattern every other
# private-endpoint-backed unit in this repo uses.

variable "resource_group_name" {
  description = "Existing resource group to deploy into (the hub network layer's RG)."
  type        = string
}

variable "subnet_id" {
  description = "ID of the existing subnet the connector VM and NAT Gateway attach to (hub's \"cloudflare-zero-trust\" subnet)."
  type        = string
}

variable "connector_subnet_prefix" {
  description = "Address prefix(es) of the existing connector subnet (var.subnet_id) — routed through the tunnel alongside spoke_cidrs so the DNS forwarder living in that subnet stays reachable."
  type        = list(string)
}

variable "spoke_cidrs" {
  description = "CIDR ranges of spoke VNets/subnets (private resources, e.g. prod) that should be reachable through the tunnel. Peering the hub to these VNets is done manually, outside this module."
  type        = list(string)
  default     = []
}

# ── Connector VM ──────────────────────────────────────────────────────────────

variable "vm_size" {
  description = "Size of the connector VM. Kept small — it only runs cloudflared and a local DNS forwarder. Change this if your region/subscription reports SkuNotAvailable/capacity restrictions for the default."
  type        = string
  default     = "Standard_D2s_v3"
}

variable "admin_username" {
  description = "Admin username for the connector VM. SSH key auth only, no password."
  type        = string
  default     = "cfconnector"
}

variable "os_image" {
  description = "OS image for the connector VM."
  type = object({
    publisher = string
    offer     = string
    sku       = string
    version   = string
  })
  default = {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }
}

# ── DNS ───────────────────────────────────────────────────────────────────────

variable "private_dns_forward_domains" {
  description = "Domain suffixes resolved via the connector's local DNS forwarder (Azure's recursive resolver) instead of Cloudflare's default resolver — needed so private-endpoint hostnames (Databricks, storage, Key Vault) resolve to their private IPs for WARP clients. Keep this in sync with the hub's actual privatelink zones (02environments/hub's 03private-dns-zones unit) — a domain listed here with no matching zone just forwards to the public resolver."
  type        = list(string)
  default = [
    "azuredatabricks.net",
    "core.windows.net",
    "vault.azure.net",
  ]
}

# ── Access control ────────────────────────────────────────────────────────────

variable "access_group_name" {
  description = "Display name for the Entra ID group this module creates. Its members get Zero Trust access to spoke_cidrs."
  type        = string
  default     = "zero-trust-private-access"
}

variable "access_group_members" {
  description = "Object IDs of Entra ID users/service principals to add to the access group at creation time. More can be added later outside Terraform."
  type        = list(string)
  default     = []
}
