# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) — do not redeclare here.

variable "resource_group_name" {
  description = "Existing resource group to deploy into (the network layer's RG)."
  type        = string
}

variable "project" {
  description = "Project name segment used in resource naming (e.g. alphaai)."
  type        = string
}

variable "instance" {
  description = "Instance number segment used in resource naming."
  type        = string
  default     = "001"
}

variable "route_tables" {
  description = "Route tables keyed by purpose (e.g. databricks-public, adf). Name defaults to rt-<location_code>-<environment>-<project>-<key>-<instance>."
  type = map(object({
    name      = optional(string)
    subnet_id = optional(string) # associate this route table with a subnet if set

    # Off by default — this test tenant has no firewall at the hub. When
    # deploying to a client tenant with a firewall at the hub (e.g.
    # Fortigate), set enable_firewall_egress = true and firewall_private_ip
    # to route this route table's default egress (0.0.0.0/0) through it.
    enable_firewall_egress = optional(bool, false)
    firewall_private_ip    = optional(string)

    routes = optional(list(object({
      name                   = string
      address_prefix         = string
      next_hop_type          = string           # VirtualAppliance, VirtualNetworkGateway, VnetLocal, Internet, or None
      next_hop_in_ip_address = optional(string) # required when next_hop_type = VirtualAppliance
    })), [])
  }))
  default = {}

  validation {
    condition     = alltrue([for rt in var.route_tables : !rt.enable_firewall_egress || rt.firewall_private_ip != null])
    error_message = "firewall_private_ip is required when enable_firewall_egress is true."
  }
}
