# subscription_id, tenant_id, location, environment, location_code, tags are
# declared in globals.tf (generated by common.hcl) — do not redeclare here.

variable "resource_group_name" {
  description = "Existing resource group to deploy into (the network layer's RG)."
  type        = string
}

variable "project" {
  description = "Project name segment used in resource naming (e.g. alphaai)."
  type        = string
}

variable "instance" {
  description = "Instance number segment used in resource naming."
  type        = string
  default     = "001"
}

variable "network_security_groups" {
  description = "NSGs keyed by purpose (e.g. databricks-public, private-endpoints, adf). Name defaults to nsg-<location_code>-<environment>-<project>-<key>-<instance>. Rules and subnet association are fully data-driven — no purpose-specific logic in this module."
  type = map(object({
    name      = optional(string)
    subnet_id = optional(string) # associate this NSG with a subnet if set

    security_rules = optional(list(object({
      name                         = string
      priority                     = number
      direction                    = string # Inbound or Outbound
      access                       = string # Allow or Deny
      protocol                     = string # Tcp, Udp, Icmp, or *
      source_port_range            = optional(string)
      source_port_ranges           = optional(list(string))
      destination_port_range       = optional(string)
      destination_port_ranges      = optional(list(string))
      source_address_prefix        = optional(string)
      source_address_prefixes      = optional(list(string))
      destination_address_prefix   = optional(string)
      destination_address_prefixes = optional(list(string))
    })), [])
  }))
  default = {}
}
